runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /images
  static_dir: build/esm-bundled/images
  secure: always

- url: /node_modules
  static_dir: build/esm-bundled/node_modules
  secure: always

- url: /src
  static_dir: build/esm-bundled/src
  secure: always

- url: /manifest.json
  static_files: build/esm-bundled/manifest.json
  upload: build/esm-bundled/manifest.json
  secure: always

- url: /service-worker.js
  static_files: build/esm-bundled/service-worker.js
  upload: build/esm-bundled/service-worker.js
  secure: always

- url: /.*
  static_files: build/esm-bundled/index.html
  upload: build/esm-bundled/index.html
  secure: always

skip_files:
  - build/es5-bundled/
  - build/es6-bundled/
  - images/
  - node_modules/
  - server/
  - src/
  - test/
